version: '3.8'

services:
  strapi:
    container_name: strapi-dev
    build:
      context: .
      target: dev
    image: strapi-mydsu:dev
    restart: unless-stopped
    env_file: .env
    environment:
      NODE_ENV: development
    volumes:
      - ./:/opt/app
    ports:
      - "1337:1337"
